package oopproject.users;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import oopproject.academic.Course;
import oopproject.academic.News;
import oopproject.academic.Report;
import oopproject.academic.Request;
import oopproject.enums.ManagerType;
import oopproject.enums.ReportType;

public class Manager extends Employee {
    private ManagerType type;
    private final List<News> news = new ArrayList<>();

    public Manager() {
    }

    public Manager(int id, String username, String password, String email,
                   double salary, LocalDate hireDate, ManagerType type) {
        super(id, username, password, email, salary, hireDate);
        this.type = type;
    }

    public void approveRegistration(Employee employee) {
    }

    public void rejectRegistration(Employee employee) {
    }

    public void assignTeacher(Course course, Teacher teacher) {
        course.addInstructor(teacher);
    }

    public Report generateReport() {
        return new Report(ReportType.COURSE_STATISTICS, "Generated by " + username);
    }

    public void createCourse(Course course) {
        course.setOpen(false);
    }

    public void openCourseForRegistration(Course course) {
        course.setOpen(true);
    }

    public void createNews(News item) {
        news.add(item);
    }

    public void manageNews(News item) {
        if (!news.contains(item)) {
            news.add(item);
        }
    }

    public List<Request> showRequests() {
        return getRequestInstance();
    }

    public Request findRequestById(long requestId) {
        return requests.stream()
                .filter(request -> request.getRequestId() == requestId)
                .findFirst()
                .orElse(null);
    }

    public Request showRequest(Request request) {
        return request;
    }

    public void reviewRequest(Request request, boolean status) {
        if (status) {
            request.approve();
        } else {
            request.reject();
        }
    }

    public void removeRequest(long requestId) {
        requests.removeIf(request -> request.getRequestId() == requestId);
    }

    public List<Request> showFinishedRequests() {
        return requests.stream()
                .filter(request -> request.getStatus() != oopproject.enums.RequestStatus.PENDING)
                .toList();
    }
}
