package oopproject.users;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import oopproject.academic.Course;
import oopproject.academic.News;
import oopproject.academic.Report;
import oopproject.academic.Request;
import oopproject.core.University;
import oopproject.enums.ManagerType;
import oopproject.enums.ReportType;
import oopproject.enums.UserType;

public class Manager extends Employee {
    private ManagerType type;
    private final List<News> news = new ArrayList<>();

    public Manager() {
        this.role = UserType.MANAGER;
    }

    public Manager(int id, String username, String password, String email,
                   double salary, LocalDate hireDate, ManagerType type) {
        super(id, username, password, email, salary, hireDate);
        this.role = UserType.MANAGER;
        this.type = type;
    }

     public void approveRegistration(Employee employee) {
        System.out.println(employee.id + employee.username + "Your registration has been approved.");
    }

    public void rejectRegistration(Employee employee) {
        System.out.println(employee.id + employee.username + "Your registration has been rejected.");
    }

    public void assignTeacher(Course course, Teacher teacher) {
        course.addInstructor(teacher);
    }

    public Report generateReport() {
        return new Report(ReportType.COURSE_STATISTICS, "Generated by " + username);
    }

    public void createCourse(Course course) {
        course.setOpen(false);
    }

    public void openCourseForRegistration(Course course) {
        course.setOpen(true);
    }

    public void createNews(News item) {
        news.add(item);
    }

    public void manageNews(News item) {
        if (!news.contains(item)) {
            news.add(item);
        }
    }

    public List<Request> showRequests() {
        return University.getInstance().getRequests();
    }

    public Request findRequestById(long requestId) {
        return University.getInstance().findRequestById(requestId).orElse(null);
    }

    public Request showRequest(Request request) {
        return request;
    }

    public boolean approveRequest(Request request) {
        if (!isManagedRequest(request)) {
            return false;
        }
        request.approve();
        University.getInstance().addLog(this, "REQUEST_APPROVED id=" + request.getRequestId());
        return true;
    }

    public boolean rejectRequest(Request request) {
        if (!isManagedRequest(request)) {
            return false;
        }
        request.reject();
        University.getInstance().addLog(this, "REQUEST_REJECTED id=" + request.getRequestId());
        return true;
    }

    public boolean commentRequest(Request request, String comment) {
        if (!isManagedRequest(request) || comment == null || comment.isBlank()) {
            return false;
        }
        request.setResponseComment(comment);
        University.getInstance().addLog(this, "REQUEST_COMMENTED id=" + request.getRequestId());
        return true;
    }

    public void removeRequest(long requestId) {
        University.getInstance().removeRequest(this, requestId);
    }

    public List<Request> showFinishedRequests() {
        return University.getInstance().getFinishedRequests();
    }

    private boolean isManagedRequest(Request request) {
        return request != null && University.getInstance().findRequestById(request.getRequestId()).isPresent();
    }
}